name: movie_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.3.0
  gap: ^3.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  flutter_riverpod: ^2.6.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  firebase_auth: ^5.3.1
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.8
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true

  assets:
    - assets/json/
